#!/usr/bin/python
# HiPerCic Project / St. Olaf College / Computer Science Dept.
##################################################################################################
# Created 7/20/2011
# Launches the docGen app with certian arguments to generate documentation for hipercore.
##################################################################################################
from hipercic.hipercore.docGen import main

print("Press the return key to generate full documentation for hipercic:")
st = raw_input("")


main.main(["./doc", ".", "-J", "..", "-E", "hipercic.apps"])
